In [4]:
! pip install chembl_webresource_client pandas numpy matplotlib

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.5.20)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.10.0)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.9 MB/s eta 0:00:00
Downloading requests_cache-1.3.2-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 6.4 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.0 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.2 url-normalize-3.0.0

In [5]:
from chembl_webresource_client.new_client import new_client
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
Target=new_client.target
Target_query=Target.search('EGFR')
Targets=pd.DataFrame.from_dict(Target_query)
Targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,EGFR/PPP1CA,17.0,False,CHEMBL4523747,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
1,[],Homo sapiens,CCN2-EGFR,17.0,False,CHEMBL5465557,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
2,[],Mus musculus,Epidermal growth factor receptor,15.0,False,CHEMBL3608,"[{'accession': 'Q01279', 'component_descriptio...",SINGLE PROTEIN,10090
3,[],Mus musculus,Protein cereblon/Epidermal growth factor receptor,13.0,False,CHEMBL6193842,"[{'accession': 'Q01279', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
4,[],Homo sapiens,Epidermal growth factor receptor,11.0,False,CHEMBL203,"[{'accession': 'P00533', 'component_descriptio...",SINGLE PROTEIN,9606
5,[],Homo sapiens,Protein cereblon/Epidermal growth factor receptor,11.0,False,CHEMBL4523680,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
6,[],Homo sapiens,Epidermal growth factor receptor,10.0,False,CHEMBL2363049,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN FAMILY,9606
7,[],Homo sapiens,MER intracellular domain/EGFR extracellular do...,10.0,False,CHEMBL3137284,"[{'accession': 'P00533', 'component_descriptio...",CHIMERIC PROTEIN,9606
8,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Epi...,10.0,False,CHEMBL4523998,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
9,[],Mus musculus,Protein cereblon/Epidermal growth factor receptor,10.0,False,CHEMBL6193841,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
10,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL1824,"[{'accession': 'P04626', 'component_descriptio...",SINGLE PROTEIN,9606
11,[],Rattus norvegicus,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL3848,"[{'accession': 'P06494', 'component_descriptio...",SINGLE PROTEIN,10116
12,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-4,9.0,False,CHEMBL3009,"[{'accession': 'Q15303', 'component_descriptio...",SINGLE PROTEIN,9606
13,[],Homo sapiens,Receptor tyrosine-protein kinase erbB-3,9.0,False,CHEMBL5838,"[{'accession': 'P21860', 'component_descriptio...",SINGLE PROTEIN,9606
14,[],Homo sapiens,Epidermal growth factor receptor and ErbB2 (HE...,9.0,False,CHEMBL2111431,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN FAMILY,9606
15,[],Mus musculus,Receptor tyrosine-protein kinase erbB-2,9.0,False,CHEMBL2311234,"[{'accession': 'P70424', 'component_descriptio...",SINGLE PROTEIN,10090
16,[],Homo sapiens,FASN/HER2,9.0,False,CHEMBL4106134,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN COMPLEX,9606
17,[],Homo sapiens,ErbB-2/ErbB-3 heterodimer,9.0,False,CHEMBL4630723,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN COMPLEX,9606
18,[],Homo sapiens,Baculoviral IAP repeat-containing protein 2/Ep...,9.0,False,CHEMBL4802031,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
19,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Rec...,9.0,False,CHEMBL5465227,"[{'accession': 'P04626', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
20,[],Homo sapiens,Microtubule-associated protein 1 light chain 3...,9.0,False,CHEMBL6066839,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
21,[],Homo sapiens,Glucose-induced degradation protein 4 homolog/...,9.0,False,CHEMBL6066845,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
22,[],Homo sapiens,E3 ubiquitin-protein ligase Mdm2/Epidermal gro...,9.0,False,CHEMBL6193792,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
23,[],Homo sapiens,UBR/Epidermal growth factor receptor,9.0,False,CHEMBL6193830,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
24,[],Homo sapiens,Protein zyg-11 homolog B/Protein zer-1 homolog...,9.0,False,CHEMBL6193837,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
25,[],Homo sapiens,E3 ubiquitin-protein ligase RNF149/Epidermal g...,9.0,False,CHEMBL6195769,"[{'accession': 'P00533', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [7]:
target_human=Targets.target_chembl_id[4]
target_human

'CHEMBL203'

In [8]:
target_human_activity=new_client.activity
res=target_human_activity.filter(target_chembl_id=target_human).filter(standard_type="IC50")
df=pd.DataFrame.from_dict(res)
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.041
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.3
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,7.82
3,None,None,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.17
4,None,None,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26595,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313764,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,130.1
26596,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313765,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,4.81
26597,None,None,29313766,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,Not_determined,None,IC50,None,None,None,None
26598,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313767,[],CHEMBL6184534,Inhibition of wildtype EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,13.08
26599,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29313803,[],CHEMBL6184543,Inhibition of EGFR (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,nM,UO_0000065,None,0.025

In [9]:
df.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value'],
      dtype='object')

In [10]:
spefic_target=df.filter(['molecule_chembl_id', 'canonical_smiles', 'standard_value', 'standard_units', 'pchembl_value', 'activity_comment', 'assay_type', 'target_chembl_id', 'type'])
spefic_target.to_csv('EGFR.csv',index=False)

In [11]:
spefic_target=pd.read_csv('EGFR.csv')
spefic_target

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.000,nM,5.11,NaN,F,CHEMBL203,IC50
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50
...,...,...,...,...,...,...,...,...,...
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50
26597,CHEMBL98,O=C(CCCCCCC(=O)Nc1ccccc1)NO,NaN,NaN,NaN,NaN,B,CHEMBL203,IC50
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50

In [12]:
remove_nan= spefic_target[spefic_target['standard_units']== 'nM']
remove_nan

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.000,nM,5.11,NaN,F,CHEMBL203,IC50
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50
...,...,...,...,...,...,...,...,...,...
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.800,nM,8.01,NaN,B,CHEMBL203,IC50
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50

In [13]:
target_type=spefic_target[spefic_target['type']== 'IC50']
target_type

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.000,nM,5.11,NaN,F,CHEMBL203,IC50
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50
...,...,...,...,...,...,...,...,...,...
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50
26597,CHEMBL98,O=C(CCCCCCC(=O)Nc1ccccc1)NO,NaN,NaN,NaN,NaN,B,CHEMBL203,IC50
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50

In [14]:
target_type.type.unique()

array(['IC50'], dtype=object)

In [15]:
target_type= target_type.dropna(subset=['canonical_smiles', 'standard_value', 'pchembl_value'])
target_type

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.000,nM,5.11,NaN,F,CHEMBL203,IC50
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50
...,...,...,...,...,...,...,...,...,...
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.800,nM,8.01,NaN,B,CHEMBL203,IC50
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50

In [16]:
comp_measure = target_type.groupby('molecule_chembl_id').size().reset_index(name='measure_count')
dup_comp= comp_measure[comp_measure['measure_count'] > 1]
dup_comp

      molecule_chembl_id  measure_count
0               CHEMBL10              2
19          CHEMBL105053              2
20          CHEMBL105436              2
28         CHEMBL1079742              4
31         CHEMBL1080506              2
...                  ...            ...
10437        CHEMBL94275              2
10445        CHEMBL96627              2
10449           CHEMBL98              2
10451        CHEMBL98248              2
10452        CHEMBL98798              2

[3939 rows x 2 columns]

In [17]:
df_no_duplicates = target_type.drop_duplicates(subset=['molecule_chembl_id'])
display(df_no_duplicates.shape)
display(df_no_duplicates)

(10454, 9)

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.00,nM,7.39,NaN,B,CHEMBL203,IC50
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.00,nM,6.77,NaN,B,CHEMBL203,IC50
6,CHEMBL137635,CN(c1ccccc1)c1ncnc2ccc(N/N=N/Cc3ccccn3)cc12,9300.00,nM,5.03,NaN,B,CHEMBL203,IC50
9,CHEMBL77085,N#CC(C#N)=Cc1cc(O)ccc1[N+](=O)[O-],96000.00,nM,4.02,NaN,B,CHEMBL203,IC50
10,CHEMBL443268,Cc1cc(C(=O)NCCN2CCOCC2)[nH]c1/C=C1\C(=O)N(C)c2...,5310.00,nM,5.28,NaN,B,CHEMBL203,IC50
...,...,...,...,...,...,...,...,...,...
26591,CHEMBL6189102,COc1ccc(Nc2ncnc3cc(OCCCC(=O)NO)c4c(c23)OCCO4)cc1,894.70,nM,6.05,NaN,B,CHEMBL203,IC50
26592,CHEMBL6193560,O=C(CCCOc1cc2ncnc(Nc3cccc(C(F)(F)F)c3)c2c2c1OC...,45.50,nM,7.34,NaN,B,CHEMBL203,IC50
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.80,nM,8.01,NaN,B,CHEMBL203,IC50
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.10,nM,6.89,NaN,B,CHEMBL203,IC50
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.81,nM,8.32,NaN,B,CHEMBL203,IC50

In [18]:
import numpy as np
target_final= target_type.copy()
target_final['pIC50']= np.log10 (target_type['standard_value']* 1e-9)
display(target_final[['molecule_chembl_id', 'standard_value', 'pIC50']])

      molecule_chembl_id  standard_value      pIC50
0            CHEMBL68920          41.000  -7.387216
1            CHEMBL68920         300.000  -6.522879
2            CHEMBL68920        7820.000  -5.106793
3            CHEMBL69960         170.000  -6.769551
4            CHEMBL69960          40.000  -7.397940
...                  ...             ...        ...
26594      CHEMBL6191667           9.800  -8.008774
26595      CHEMBL6192203         130.100  -6.885723
26596      CHEMBL6191199           4.810  -8.317855
26598          CHEMBL939          13.080  -7.883392
26599        CHEMBL29197           0.025 -10.602060

[18629 rows x 3 columns]

In [19]:
def bioactivity (IC50_value):
  if IC50_value <= 1000:
    return 'Active'
  elif IC50_value >= 10000:
    return 'Inactive'
  else:
    return 'Intermediate'

target_final['Bioactivity class']= target_final['standard_value'].apply(bioactivity)
target_final

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type,pIC50,Bioactivity class
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50,-7.387216,Active
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50,-6.522879,Active
2,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,7820.000,nM,5.11,NaN,F,CHEMBL203,IC50,-5.106793,Intermediate
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50,-6.769551,Active
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50,-7.397940,Active
...,...,...,...,...,...,...,...,...,...,...,...
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.800,nM,8.01,NaN,B,CHEMBL203,IC50,-8.008774,Active
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50,-6.885723,Active
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50,-8.317855,Active
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50,-7.883392,Active
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50,-10.602060,Active

In [20]:
target_final['Bioactivity class'].value_counts()

Bioactivity class
Active          14597
Intermediate     2884
Inactive         1148
Name: count, dtype: int64

In [21]:
target_final_filter= target_final[target_final['Bioactivity class'] != 'Intermediate'].copy()
target_final_filter

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type,pIC50,Bioactivity class
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50,-7.387216,Active
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50,-6.522879,Active
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50,-6.769551,Active
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50,-7.397940,Active
5,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,440.000,nM,6.36,NaN,F,CHEMBL203,IC50,-6.356547,Active
...,...,...,...,...,...,...,...,...,...,...,...
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.800,nM,8.01,NaN,B,CHEMBL203,IC50,-8.008774,Active
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50,-6.885723,Active
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50,-8.317855,Active
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50,-7.883392,Active
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50,-10.602060,Active

In [22]:
!pip install rdkit

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2026.3.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [23]:
import rdkit.Chem as Chem
import rdkit.Chem.Descriptors as Descriptors
import pandas as pd
import numpy as np

def calculate_smile(smiles):
  mol = Chem.MolFromSmiles(smiles)
  if mol is None: # Check if mol object was successfully created
    return [np.nan] * 4
  else:
    Mw = Descriptors.MolWt(mol)
    LogP = Descriptors.MolLogP(mol)
    NumHDonors = Descriptors.NumHDonors(mol)
    NumHAcceptors = Descriptors.NumHAcceptors(mol)
    return [Mw, LogP, NumHDonors, NumHAcceptors]

target_final_filter[['Mw', 'LogP', 'NumHDonors', 'NumHAcceptors']]= target_final_filter['canonical_smiles'].apply(lambda x: pd.Series(calculate_smile(x)))
display(target_final_filter)

,molecule_chembl_id,canonical_smiles,standard_value,standard_units,pchembl_value,activity_comment,assay_type,target_chembl_id,type,pIC50,Bioactivity class,Mw,LogP,NumHDonors,NumHAcceptors
0,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,41.000,nM,7.39,NaN,B,CHEMBL203,IC50,-7.387216,Active,383.814,4.45034,3.0,4.0
1,CHEMBL68920,Cc1cc(C)c(/C=C2\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)...,300.000,nM,6.52,NaN,F,CHEMBL203,IC50,-6.522879,Active,383.814,4.45034,3.0,4.0
3,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,170.000,nM,6.77,NaN,B,CHEMBL203,IC50,-6.769551,Active,482.903,3.61432,3.0,6.0
4,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,40.000,nM,7.40,NaN,F,CHEMBL203,IC50,-7.397940,Active,482.903,3.61432,3.0,6.0
5,CHEMBL69960,Cc1cc(C(=O)N2CCOCC2)[nH]c1/C=C1\C(=O)Nc2ncnc(N...,440.000,nM,6.36,NaN,F,CHEMBL203,IC50,-6.356547,Active,482.903,3.61432,3.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26594,CHEMBL6191667,O=C(CCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,9.800,nM,8.01,NaN,B,CHEMBL203,IC50,-8.008774,Active,444.875,3.85250,3.0,8.0
26595,CHEMBL6192203,O=C(CCCCCOc1cc2ncnc(Nc3ccccc3Cl)c2c2c1OCCO2)NO,130.100,nM,6.89,NaN,B,CHEMBL203,IC50,-6.885723,Active,458.902,4.24260,3.0,8.0
26596,CHEMBL6191199,O=C(CCCCCOc1cc2ncnc(Nc3cccc(Cl)c3)c2c2c1OCCO2)NO,4.810,nM,8.32,NaN,B,CHEMBL203,IC50,-8.317855,Active,458.902,4.24260,3.0,8.0
26598,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,13.080,nM,7.88,NaN,B,CHEMBL203,IC50,-7.883392,Active,446.910,4.27560,1.0,7.0
26599,CHEMBL29197,COc1cc2ncnc(Nc3cccc(Br)c3)c2cc1OC,0.025,nM,10.60,NaN,B,CHEMBL203,IC50,-10.602060,Active,360.211,4.15310,1.0,5.0